# Generated by Django 4.0 on 2022-01-31 08:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='unknown', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
                ('receiver', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='authentication.user')),
            ],
        ),
    ]
