# Generated by Django 4.0 on 2022-01-13 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('networking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_invites', to='authentication.user'),
        ),
    ]
