# Generated by Django 4.0 on 2022-01-14 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('networking', '0005_alter_connectrequest_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectnotification',
            name='initiated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='connectnotification',
            name='receiver',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='connectnotification',
            name='type',
            field=models.CharField(default='connect-request', max_length=255),
        ),
    ]
